-- ============================================
-- Frileux — Taste Profile + Brands seed
-- ============================================

create extension if not exists pg_trgm;

alter table public.profiles
  add column if not exists gender_presentation text
    check (gender_presentation in ('menswear', 'womenswear', 'both')),
  add column if not exists style_universes text[] not null default '{}',
  add column if not exists favorite_brands text[] not null default '{}',
  add column if not exists avoid_tags text[] not null default '{}',
  add column if not exists fit_preference text
    check (fit_preference in ('relaxed', 'regular', 'slim'));

-- ============================================
-- BRANDS (seed catalog for autocomplete)
-- universe tags: minimal, workwear, streetwear, techwear, gorpcore, preppy,
--                archive, tailoring, y2k, quiet luxury, heritage, contemporary
-- tier: luxury | designer | contemporary | street | technical | heritage
-- ============================================
create table if not exists public.brands (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  universe text[] not null default '{}',
  tier text check (tier in ('luxury', 'designer', 'contemporary', 'street', 'technical', 'heritage')),
  created_at timestamptz not null default now()
);

create index if not exists idx_brands_name_trgm on public.brands using gin (name gin_trgm_ops);

alter table public.brands enable row level security;

drop policy if exists "Anyone can read brands" on public.brands;
create policy "Anyone can read brands"
  on public.brands for select
  using (true);

insert into public.brands (name, slug, universe, tier) values
  -- ===== LUXURY HOUSES =====
  ('Maison Margiela',         'maison-margiela',         array['archive','tailoring','quiet luxury'], 'luxury'),
  ('Lemaire',                 'lemaire',                 array['minimal','quiet luxury','tailoring'], 'luxury'),
  ('The Row',                 'the-row',                 array['minimal','quiet luxury'],             'luxury'),
  ('Bottega Veneta',          'bottega-veneta',          array['quiet luxury','minimal'],             'luxury'),
  ('Loewe',                   'loewe',                   array['archive','quiet luxury'],             'luxury'),
  ('Prada',                   'prada',                   array['archive','tailoring'],                'luxury'),
  ('Miu Miu',                 'miu-miu',                 array['archive','y2k'],                      'luxury'),
  ('Jil Sander',              'jil-sander',              array['minimal','tailoring'],                'luxury'),
  ('Rick Owens',              'rick-owens',              array['archive'],                            'luxury'),
  ('Comme des Garçons',       'comme-des-garcons',       array['archive'],                            'luxury'),
  ('Yohji Yamamoto',          'yohji-yamamoto',          array['archive','tailoring'],                'luxury'),
  ('Issey Miyake',            'issey-miyake',            array['archive','minimal'],                  'luxury'),
  ('Dries Van Noten',         'dries-van-noten',         array['archive','tailoring'],                'luxury'),
  ('Khaite',                  'khaite',                  array['quiet luxury','minimal'],             'luxury'),
  ('Toteme',                  'toteme',                  array['minimal','quiet luxury'],             'luxury'),
  ('Saint Laurent',           'saint-laurent',           array['tailoring','archive'],                'luxury'),
  ('Balenciaga',              'balenciaga',              array['archive','streetwear'],               'luxury'),
  ('Celine',                  'celine',                  array['minimal','quiet luxury'],             'luxury'),
  ('Hermès',                  'hermes',                  array['quiet luxury','heritage'],            'luxury'),
  ('Chanel',                  'chanel',                  array['tailoring','heritage'],               'luxury'),
  ('Dior',                    'dior',                    array['tailoring','archive'],                'luxury'),
  ('Gucci',                   'gucci',                   array['archive','contemporary'],             'luxury'),
  ('Louis Vuitton',           'louis-vuitton',           array['heritage','contemporary'],            'luxury'),
  ('Valentino',               'valentino',               array['tailoring','contemporary'],           'luxury'),
  ('Givenchy',                'givenchy',                array['tailoring','contemporary'],           'luxury'),
  ('Fendi',                   'fendi',                   array['heritage','contemporary'],            'luxury'),
  ('Versace',                 'versace',                 array['archive','y2k'],                      'luxury'),
  ('Burberry',                'burberry',                array['heritage','tailoring'],               'luxury'),
  ('Brunello Cucinelli',      'brunello-cucinelli',      array['quiet luxury','tailoring'],           'luxury'),
  ('Loro Piana',              'loro-piana',              array['quiet luxury','minimal'],             'luxury'),
  ('Zegna',                   'zegna',                   array['quiet luxury','tailoring'],           'luxury'),
  ('Tom Ford',                'tom-ford',                array['tailoring','quiet luxury'],           'luxury'),
  ('Berluti',                 'berluti',                 array['tailoring','heritage'],               'luxury'),
  ('Thom Browne',             'thom-browne',             array['tailoring','preppy'],                 'luxury'),
  ('Stella McCartney',        'stella-mccartney',        array['minimal','contemporary'],             'luxury'),
  ('Alexander McQueen',       'alexander-mcqueen',       array['archive','tailoring'],                'luxury'),
  ('Ann Demeulemeester',      'ann-demeulemeester',      array['archive','tailoring'],                'luxury'),
  ('Junya Watanabe',          'junya-watanabe',          array['archive','workwear'],                 'luxury'),
  ('Undercover',              'undercover',              array['archive','streetwear'],               'luxury'),
  ('Marni',                   'marni',                   array['archive','contemporary'],             'luxury'),
  ('Helmut Lang',             'helmut-lang',             array['minimal','archive'],                  'luxury'),
  ('Moncler',                 'moncler',                 array['techwear','quiet luxury'],            'luxury'),

  -- ===== DESIGNER =====
  ('Jacquemus',               'jacquemus',               array['contemporary'],                       'designer'),
  ('Wales Bonner',            'wales-bonner',            array['tailoring','archive'],                'designer'),
  ('Martine Rose',            'martine-rose',            array['archive','streetwear'],               'designer'),
  ('Kiko Kostadinov',         'kiko-kostadinov',         array['archive','techwear'],                 'designer'),
  ('Maison Mihara Yasuhiro',  'mihara-yasuhiro',         array['archive','streetwear'],               'designer'),
  ('Sacai',                   'sacai',                   array['archive','techwear'],                 'designer'),
  ('Y/Project',               'y-project',               array['archive','contemporary'],             'designer'),
  ('JW Anderson',             'jw-anderson',             array['contemporary','archive'],             'designer'),
  ('Coperni',                 'coperni',                 array['contemporary','techwear'],            'designer'),
  ('Courrèges',               'courreges',               array['archive','minimal'],                  'designer'),
  ('Mugler',                  'mugler',                  array['archive','y2k'],                      'designer'),
  ('Acne Studios',            'acne-studios',            array['minimal','contemporary'],             'designer'),
  ('Our Legacy',              'our-legacy',              array['workwear','minimal','tailoring'],     'designer'),
  ('Auralee',                 'auralee',                 array['minimal','quiet luxury'],             'designer'),
  ('Margaret Howell',         'margaret-howell',         array['workwear','tailoring','heritage'],    'designer'),
  ('Studio Nicholson',        'studio-nicholson',        array['minimal','workwear'],                 'designer'),
  ('Sunflower',               'sunflower',               array['minimal'],                            'designer'),
  ('Drake''s',                'drakes',                  array['tailoring','heritage','preppy'],      'designer'),
  ('Kapital',                 'kapital',                 array['workwear','archive'],                 'designer'),
  ('Engineered Garments',     'engineered-garments',     array['workwear','heritage'],                'designer'),
  ('Visvim',                  'visvim',                  array['workwear','heritage','archive'],      'designer'),
  ('Needles',                 'needles',                 array['archive','streetwear'],               'designer'),
  ('Officine Générale',       'officine-generale',       array['tailoring','minimal'],                'designer'),
  ('De Bonne Facture',        'de-bonne-facture',        array['tailoring','heritage'],               'designer'),
  ('Lardini',                 'lardini',                 array['tailoring','heritage'],               'designer'),
  ('Boglioli',                'boglioli',                array['tailoring','heritage'],               'designer'),
  ('Beams Plus',              'beams-plus',              array['preppy','workwear','heritage'],       'designer'),
  ('Beams',                   'beams',                   array['contemporary','workwear'],            'designer'),
  ('United Arrows',           'united-arrows',           array['contemporary','tailoring'],           'designer'),
  ('Nanamica',                'nanamica',                array['techwear','workwear'],                'designer'),
  ('White Mountaineering',    'white-mountaineering',    array['techwear','gorpcore'],                'designer'),
  ('Wtaps',                   'wtaps',                   array['workwear','streetwear'],              'designer'),
  ('Neighborhood',            'neighborhood',            array['workwear','streetwear'],              'designer'),
  ('Human Made',              'human-made',              array['heritage','streetwear'],              'designer'),
  ('A Cold Wall',             'a-cold-wall',             array['techwear','streetwear'],              'designer'),
  ('Y-3',                     'y-3',                     array['techwear','streetwear'],              'designer'),
  ('MM6 Maison Margiela',     'mm6',                     array['archive','contemporary'],             'designer'),
  ('Bode',                    'bode',                    array['archive','heritage','workwear'],      'designer'),
  ('Story Mfg.',              'story-mfg',               array['heritage','workwear'],                'designer'),
  ('Phipps',                  'phipps',                  array['workwear','heritage'],                'designer'),
  ('Nicholas Daley',          'nicholas-daley',          array['heritage','tailoring'],               'designer'),
  ('S.S. Daley',              'ss-daley',                array['preppy','tailoring'],                 'designer'),
  ('Casablanca',              'casablanca',              array['preppy','contemporary'],              'designer'),
  ('Rhude',                   'rhude',                   array['streetwear','contemporary'],          'designer'),
  ('Amiri',                   'amiri',                   array['streetwear','y2k'],                   'designer'),
  ('Palm Angels',             'palm-angels',             array['streetwear','y2k'],                   'designer'),
  ('Marine Serre',            'marine-serre',            array['techwear','contemporary'],            'designer'),
  ('Botter',                  'botter',                  array['archive','contemporary'],             'designer'),
  ('GmbH',                    'gmbh',                    array['techwear','contemporary'],            'designer'),
  ('Charles Jeffrey Loverboy','charles-jeffrey-loverboy',array['archive','contemporary'],             'designer'),
  ('Mowalola',                'mowalola',                array['y2k','contemporary'],                 'designer'),
  ('Hed Mayner',              'hed-mayner',              array['archive','tailoring'],                'designer'),
  ('Magliano',                'magliano',                array['archive','tailoring'],                'designer'),
  ('Ottolinger',              'ottolinger',              array['archive','y2k'],                      'designer'),
  ('Diotima',                 'diotima',                 array['contemporary','minimal'],             'designer'),
  ('Conner Ives',             'conner-ives',             array['contemporary','y2k'],                 'designer'),
  ('Chopova Lowena',          'chopova-lowena',          array['archive','contemporary'],             'designer'),
  ('Cecilie Bahnsen',         'cecilie-bahnsen',         array['contemporary','quiet luxury'],        'designer'),
  ('Stine Goya',              'stine-goya',              array['contemporary'],                       'designer'),
  ('Baserange',               'baserange',               array['minimal','quiet luxury'],             'designer'),
  ('Lauren Manoogian',        'lauren-manoogian',        array['minimal','quiet luxury'],             'designer'),
  ('Eckhaus Latta',           'eckhaus-latta',           array['archive','contemporary'],             'designer'),
  ('Collina Strada',          'collina-strada',          array['contemporary','y2k'],                 'designer'),
  ('Paloma Wool',             'paloma-wool',             array['contemporary','minimal'],             'designer'),
  ('Sandy Liang',             'sandy-liang',             array['contemporary','y2k'],                 'designer'),
  ('Simone Rocha',            'simone-rocha',            array['archive','contemporary'],             'designer'),
  ('Lownn',                   'lownn',                   array['minimal','quiet luxury'],             'designer'),
  ('Rejina Pyo',              'rejina-pyo',              array['contemporary','minimal'],             'designer'),
  ('Nensi Dojaka',            'nensi-dojaka',            array['contemporary','y2k'],                 'designer'),
  ('Supriya Lele',            'supriya-lele',            array['contemporary','y2k'],                 'designer'),
  ('Kwaidan Editions',        'kwaidan-editions',        array['archive','tailoring'],                'designer'),
  ('Peter Do',                'peter-do',                array['minimal','tailoring'],                'designer'),
  ('Aspesi',                  'aspesi',                  array['minimal','heritage'],                 'designer'),
  ('Fear of God',             'fear-of-god',             array['streetwear','quiet luxury'],          'designer'),
  ('Off-White',               'off-white',               array['streetwear','contemporary'],          'designer'),
  ('Vetements',               'vetements',               array['streetwear','archive'],               'designer'),
  ('1017 ALYX 9SM',           'alyx',                    array['techwear','streetwear'],              'designer'),
  ('Ambush',                  'ambush',                  array['streetwear','contemporary'],          'designer'),
  ('Common Projects',         'common-projects',         array['minimal','quiet luxury'],             'designer'),
  ('Bianca Saunders',         'bianca-saunders',         array['archive','contemporary'],             'designer'),
  ('AMI Paris',               'ami-paris',               array['tailoring','contemporary'],           'designer'),

  -- ===== CONTEMPORARY =====
  ('A.P.C.',                  'apc',                     array['minimal','workwear'],                 'contemporary'),
  ('Norse Projects',          'norse-projects',          array['minimal','workwear'],                 'contemporary'),
  ('Aimé Leon Dore',          'aime-leon-dore',          array['preppy','streetwear'],                'contemporary'),
  ('Maison Kitsuné',          'maison-kitsune',          array['preppy','contemporary'],              'contemporary'),
  ('Sandro',                  'sandro',                  array['tailoring','contemporary'],           'contemporary'),
  ('Maje',                    'maje',                    array['contemporary'],                       'contemporary'),
  ('Sézane',                  'sezane',                  array['contemporary','preppy'],              'contemporary'),
  ('Rouje',                   'rouje',                   array['contemporary'],                       'contemporary'),
  ('Reformation',             'reformation',             array['contemporary'],                       'contemporary'),
  ('Ganni',                   'ganni',                   array['contemporary'],                       'contemporary'),
  ('Filippa K',               'filippa-k',               array['minimal'],                            'contemporary'),
  ('Cos',                     'cos',                     array['minimal'],                            'contemporary'),
  ('Arket',                   'arket',                   array['minimal'],                            'contemporary'),
  ('Uniqlo',                  'uniqlo',                  array['minimal'],                            'contemporary'),
  ('Uniqlo U',                'uniqlo-u',                array['minimal','workwear'],                 'contemporary'),
  ('Muji',                    'muji',                    array['minimal'],                            'contemporary'),
  ('Everlane',                'everlane',                array['minimal'],                            'contemporary'),
  ('Asket',                   'asket',                   array['minimal','quiet luxury'],             'contemporary'),
  ('Saturdays NYC',           'saturdays-nyc',           array['minimal','contemporary'],             'contemporary'),
  ('Rag & Bone',              'rag-bone',                array['contemporary','tailoring'],           'contemporary'),
  ('John Elliott',            'john-elliott',            array['streetwear','contemporary'],          'contemporary'),
  ('Lady White Co',           'lady-white-co',           array['minimal'],                            'contemporary'),
  ('Buck Mason',              'buck-mason',              array['heritage','workwear'],                'contemporary'),
  ('Todd Snyder',             'todd-snyder',             array['heritage','tailoring'],               'contemporary'),
  ('Tekla',                   'tekla',                   array['minimal'],                            'contemporary'),
  ('Tibi',                    'tibi',                    array['minimal','tailoring'],                'contemporary'),
  ('Holzweiler',              'holzweiler',              array['minimal','contemporary'],             'contemporary'),
  ('By Malene Birger',        'by-malene-birger',        array['minimal','contemporary'],             'contemporary'),
  ('Wood Wood',               'wood-wood',               array['minimal','contemporary'],             'contemporary'),
  ('Han Kjøbenhavn',          'han-kjobenhavn',          array['minimal','contemporary'],             'contemporary'),
  ('Soulland',                'soulland',                array['streetwear','contemporary'],          'contemporary'),
  ('Stockholm Surfboard Club','stockholm-surfboard-club',array['streetwear','contemporary'],          'contemporary'),
  ('Tory Burch',              'tory-burch',              array['preppy','contemporary'],              'contemporary'),
  ('Proenza Schouler',        'proenza-schouler',        array['contemporary','tailoring'],           'contemporary'),
  ('Adsum',                   'adsum',                   array['workwear','techwear'],                'contemporary'),
  ('Camper',                  'camper',                  array['contemporary','minimal'],             'contemporary'),
  ('Rowing Blazers',          'rowing-blazers',          array['preppy','heritage'],                  'contemporary'),
  ('Diesel',                  'diesel',                  array['y2k','contemporary'],                 'contemporary'),

  -- ===== STREETWEAR =====
  ('Stüssy',                  'stussy',                  array['streetwear'],                         'street'),
  ('Carhartt WIP',            'carhartt-wip',            array['workwear','streetwear'],              'street'),
  ('Patta',                   'patta',                   array['streetwear'],                         'street'),
  ('Awake NY',                'awake-ny',                array['streetwear'],                         'street'),
  ('Supreme',                 'supreme',                 array['streetwear'],                         'street'),
  ('Palace',                  'palace',                  array['streetwear'],                         'street'),
  ('Bape',                    'bape',                    array['streetwear','y2k'],                   'street'),
  ('Heron Preston',           'heron-preston',           array['streetwear','techwear'],              'street'),
  ('Cactus Plant Flea Market','cactus-plant-flea-market',array['streetwear','contemporary'],          'street'),
  ('Brain Dead',              'brain-dead',              array['streetwear','contemporary'],          'street'),
  ('Online Ceramics',         'online-ceramics',         array['streetwear','contemporary'],          'street'),
  ('Noah NY',                 'noah-ny',                 array['streetwear','preppy'],                'street'),
  ('Kith',                    'kith',                    array['streetwear','preppy'],                'street'),
  ('Fear of God Essentials',  'essentials',              array['streetwear','minimal'],               'street'),
  ('Vans',                    'vans',                    array['streetwear','heritage'],              'street'),
  ('Nike',                    'nike',                    array['streetwear','techwear'],              'street'),
  ('Adidas',                  'adidas',                  array['streetwear','heritage'],              'street'),
  ('Asics',                   'asics',                   array['streetwear','techwear'],              'street'),
  ('Crocs',                   'crocs',                   array['streetwear','contemporary'],          'street'),
  ('ERL',                     'erl',                     array['streetwear','y2k'],                   'street'),

  -- ===== TECHNICAL / GORPCORE =====
  ('Arc''teryx',              'arcteryx',                array['techwear','gorpcore'],                'technical'),
  ('Veilance',                'veilance',                array['techwear','minimal'],                 'technical'),
  ('Salomon',                 'salomon',                 array['gorpcore','techwear'],                'technical'),
  ('And Wander',              'and-wander',              array['gorpcore','techwear'],                'technical'),
  ('Snow Peak',               'snow-peak',               array['gorpcore','heritage'],                'technical'),
  ('Goldwin',                 'goldwin',                 array['techwear','gorpcore'],                'technical'),
  ('ROA',                     'roa',                     array['techwear','gorpcore'],                'technical'),
  ('The North Face',          'the-north-face',          array['gorpcore','techwear'],                'technical'),
  ('Patagonia',               'patagonia',               array['gorpcore','techwear','heritage'],     'technical'),
  ('Mammut',                  'mammut',                  array['gorpcore','techwear'],                'technical'),
  ('Klättermusen',            'klattermusen',            array['gorpcore','techwear'],                'technical'),
  ('Houdini',                 'houdini',                 array['gorpcore','techwear'],                'technical'),
  ('Norrøna',                 'norrona',                 array['gorpcore','techwear'],                'technical'),
  ('Mountain Hardwear',       'mountain-hardwear',       array['gorpcore','techwear'],                'technical'),
  ('Columbia',                'columbia',                array['gorpcore','techwear'],                'technical'),
  ('Helly Hansen',            'helly-hansen',            array['techwear','heritage'],                'technical'),
  ('Fjällräven',              'fjallraven',              array['gorpcore','heritage'],                'technical'),
  ('Descente Allterrain',     'descente-allterrain',     array['techwear','gorpcore'],                'technical'),
  ('Pas Normal Studios',      'pas-normal-studios',      array['techwear'],                           'technical'),
  ('Acronym',                 'acronym',                 array['techwear'],                           'technical'),
  ('Stone Island',            'stone-island',            array['techwear','streetwear'],              'technical'),
  ('CP Company',              'cp-company',              array['techwear','heritage'],                'technical'),
  ('Hoka',                    'hoka',                    array['gorpcore','techwear'],                'technical'),
  ('On Running',              'on-running',              array['techwear','gorpcore'],                'technical'),

  -- ===== HERITAGE / WORKWEAR =====
  ('Levi''s',                 'levis',                   array['heritage','workwear'],                'heritage'),
  ('Levi''s Vintage',         'levis-vintage',           array['heritage','workwear'],                'heritage'),
  ('orSlow',                  'orslow',                  array['heritage','workwear'],                'heritage'),
  ('Big John',                'big-john',                array['heritage','workwear'],                'heritage'),
  ('Iron Heart',              'iron-heart',              array['heritage','workwear'],                'heritage'),
  ('Filson',                  'filson',                  array['heritage','workwear'],                'heritage'),
  ('Red Wing',                'red-wing',                array['heritage','workwear'],                'heritage'),
  ('Wrangler',                'wrangler',                array['heritage','workwear'],                'heritage'),
  ('Lee',                     'lee',                     array['heritage','workwear'],                'heritage'),
  ('Dickies',                 'dickies',                 array['workwear','streetwear'],              'heritage'),
  ('Carhartt',                'carhartt',                array['workwear','heritage'],                'heritage'),
  ('Pendleton',               'pendleton',               array['heritage','workwear'],                'heritage'),
  ('Barbour',                 'barbour',                 array['heritage','tailoring'],               'heritage'),
  ('Gloverall',               'gloverall',               array['heritage','tailoring'],               'heritage'),
  ('Mackintosh',              'mackintosh',              array['heritage','minimal'],                 'heritage'),
  ('Sunspel',                 'sunspel',                 array['minimal','heritage'],                 'heritage'),
  ('John Smedley',            'john-smedley',            array['heritage','minimal'],                 'heritage'),
  ('Anderson & Sheppard',     'anderson-sheppard',       array['tailoring','heritage'],               'heritage'),
  ('Inverallan',              'inverallan',              array['heritage','workwear'],                'heritage'),
  ('Polo Ralph Lauren',       'polo-ralph-lauren',       array['preppy','heritage'],                  'heritage'),
  ('J.Press',                 'j-press',                 array['preppy','heritage','tailoring'],      'heritage'),
  ('Brooks Brothers',         'brooks-brothers',         array['preppy','heritage','tailoring'],      'heritage'),
  ('New Balance',             'new-balance',             array['gorpcore','heritage'],                'heritage'),
  ('Converse',                'converse',                array['heritage','streetwear'],              'heritage'),
  ('Birkenstock',             'birkenstock',             array['heritage','minimal'],                 'heritage'),
  ('Clarks Originals',        'clarks-originals',        array['heritage','workwear'],                'heritage'),
  ('Dr. Martens',             'dr-martens',              array['heritage','streetwear'],              'heritage')
on conflict (slug) do nothing;
